### ISSUE TITLE
Redirect xxx.lanl.gov to arxiv

### ISSUE THREAD

**Issue by MJKirk** [imurray/redirectify#12]
First, thanks for taking inspiration from my fork and pulling in my inspirehep redirect changes! :+1: 

Could you change the xxx.lanl.gov redirect so it also redirects to the arxiv?
(See my commit: https://github.com/MJKirk/redirectify/commit/0b0551b458b78af6f194fbc2e1c6a9b67b74df33)
Since currently any lanl link just gets redirected to an error page, just doing pdf -> abs isn't much use.
Lot's of old papers have lanl hyperlinks in them, so doing this automatically would be great.

I can submit a pull request if you want.

**Comment by imurray** [comment]
Sorry about that. I'd taken its temporary maintenance error message at face value. I should have been more careful.

I've pushed a fix 09b9802. If you could check I haven't messed up, that would be great. I'll probably wait a few days before pushing to the addons stores again again.

**Comment by MJKirk** [comment]
No worries, it was only after I saw their error page a few times I realised it was probably just dead.

Just tried out your version, it works for me, so I'm happy.
Feel free to close this issue now, or when you update the store versions.

**Comment by imurray** [comment]
Store versions now updated.
