### ISSUE TITLE
Permissions are scary

### ISSUE THREAD

**Issue by imurray** [imurray/redirectify#3]
_Is it possible to not require the "do anything on all sites you visit" permission?_ — [James Darpinian on Twitter](https://twitter.com/modeless/status/970434436159348736)

I could hard-code the domains into the manifest, if there isn't much demand for making the rules user-extensible?

I'm not sure about the "do anything" part — the permissions for web-extensions seem quite coarse-grained.

**Comment by jdarpinian** [comment]
Yes, putting the domains in the manifest is exactly the right thing. "Read and change all your data on the websites you visit" is an incredibly powerful permission. If anyone ever hijacked your developer account they could maliciously update the extension and silently start stealing bank accounts, Google/Facebook passwords, Bitcoin, etc from your users.

**Comment by imurray** [comment]
Version 0.2 addresses this issue as best I can.
